version: '2'

services:
  wordpress:
    image: wordpress:5.8.3-php7.4-apache
    volumes:
      - .:/var/www/html/wp-content/themes/wp_infinity_theme
      - ./docker/plugins:/var/www/html/wp-content/plugins
      - ./docker/uploads:/var/www/html/wp-content/uploads
      - ./docker/themes:/var/www/html/wp-content/themes
      - ./docker/tmp:/var/www/html/wp-content/tmp
    ports:
      - "80:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DEBUG : 1
      WORDPRESS_CONFIG_EXTRA: |
        define( 'WP_DEBUG_LOG', 'wp-content/tmp/debug.log' );
        define( 'WP_DEBUG_DISPLAY', false );
        define( 'SAVEQUERIES', true );
        if ( strpos($_SERVER['REQUEST_URI'], 'misfinancas' ) === 0) {
            define ('WPLANG', 'pt_BR');
        } else {
            define ('WPLANG', 'en_US');
        }
    depends_on:
      - db
  db:
    image: mysql:5.7
    restart: always
    ports:
      - 3306
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
